# Generated by Django 5.1 on 2024-10-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=45)),
                ('emailaddress', models.CharField(max_length=50)),
                ('msgarea', models.TextField()),
                ('enquirydate', models.CharField(max_length=30)),
            ],
        ),
    ]
